import json
import os

# 生成 205 題涵蓋《農會法》與《農會法施行細則》全條文之精準題庫
questions = []

# ==============================================================================
# 單選題 (Single Choice Questions: s1 ~ s135)
# ==============================================================================
single_questions = [
    # 總則
    {"id": "s1", "type": "single", "chapter": "總則", "article": "農會法第1條", "question": "依農會法第一條規定，下列何者「非」農會之設立宗旨？", "options": [{"key": "A", "text": "保障農民權益"}, {"key": "B", "text": "提高農民知識技能"}, {"key": "C", "text": "經營農產品壟斷市場"}, {"key": "D", "text": "促進農業現代化，改善農民生活"}], "correctAnswers": ["C"], "explanation": "依農會法第1條規定：農會以保障農民權益，提高農民知識技能，促進農業現代化，增加生產收益，改善農民生活，發展農村經濟為宗旨。"},
    {"id": "s2", "type": "single", "chapter": "總則", "article": "農會法第2條", "question": "依農會法規定，農會之法律地位為何？", "options": [{"key": "A", "text": "行政機關"}, {"key": "B", "text": "法人"}, {"key": "C", "text": "合夥組織"}, {"key": "D", "text": "獨資企業"}], "correctAnswers": ["B"], "explanation": "依農會法第2條明確規定：「農會為法人。」"},
    {"id": "s3", "type": "single", "chapter": "總則", "article": "農會法第3條", "question": "在縣（市），農會之主管機關為何者？", "options": [{"key": "A", "text": "農業部"}, {"key": "B", "text": "縣（市）農會"}, {"key": "C", "text": "縣（市）政府"}, {"key": "D", "text": "縣（市）議會"}], "correctAnswers": ["C"], "explanation": "依農會法第3條：農會之主管機關，在中央為行政院農業委員會（現農業部）；在直轄市為直轄市政府；在縣（市）為縣（市）政府。"},
    {"id": "s4", "type": "single", "chapter": "總則", "article": "農會法第3條", "question": "在中央，農會之主管機關為何者？", "options": [{"key": "A", "text": "內政部"}, {"key": "B", "text": "行政院農業委員會（現農業部）"}, {"key": "C", "text": "經濟部"}, {"key": "D", "text": "國家發展委員會"}], "correctAnswers": ["B"], "explanation": "依農會法第3條：農會之主管機關，在中央為行政院農業委員會（現農業部）。"},
    {"id": "s5", "type": "single", "chapter": "總則", "article": "農會法施行細則第2條", "question": "依農會法施行細則規定，直轄市及縣（市）主管機關之執行單位為何？", "options": [{"key": "A", "text": "各該政府之農業行政部門"}, {"key": "B", "text": "各該直轄市或縣市農會"}, {"key": "C", "text": "各該地方法院"}, {"key": "D", "text": "各該稅務稽徵機關"}], "correctAnswers": ["A"], "explanation": "依農會法施行細則第2條：本法第三條直轄市及縣（市）主管機關之執行單位，為各該政府之農業行政部門。"},
    {"id": "s6", "type": "single", "chapter": "總則", "article": "農會法施行細則第3條", "question": "關於目的事業主管機關對農會之指導監督，依法應如何辦理？", "options": [{"key": "A", "text": "逕由目的事業主管機關單獨處理"}, {"key": "B", "text": "應各就其主管業務會同主管機關為之"}, {"key": "C", "text": "授權由農會理事會自行決定"}, {"key": "D", "text": "報請司法院核准"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第3條：本法第三條關於目的事業主管機關對農會之指導監督，應各就其主管業務會同主管機關為之。"},

    # 任務
    {"id": "s7", "type": "single", "chapter": "任務", "article": "農會法第4條", "question": "下列何者「非」農會法第四條所規定之農會任務？", "options": [{"key": "A", "text": "保障農民權益、傳播農事法令"}, {"key": "B", "text": "優良種籽及肥料之推廣"}, {"key": "C", "text": "核發地政與建物登記謄本"}, {"key": "D", "text": "農畜產品之運銷、倉儲及加工"}], "correctAnswers": ["C"], "explanation": "依農會法第4條，核發地政謄本屬於地政機關之公權力行政業務，非農會任務。"},
    {"id": "s8", "type": "single", "chapter": "任務", "article": "農會法第4條", "question": "農會舉辦第四條第一項事業關於免稅部分，應參照下列何種法規辦理？", "options": [{"key": "A", "text": "所得稅法與營業稅法"}, {"key": "B", "text": "農業發展條例及合作社法"}, {"key": "C", "text": "關稅法與印花稅法"}, {"key": "D", "text": "商業登記法"}], "correctAnswers": ["B"], "explanation": "依農會法第4條第2項：農會舉辦前項事業關於免稅部分，應參照農業發展條例及合作社法有關規定辦理；其免稅範圍，由行政院定之。"},
    {"id": "s9", "type": "single", "chapter": "任務", "article": "農會法第4條", "question": "農會辦理第四條第一項之各項任務，依法應如何列入規劃？", "options": [{"key": "A", "text": "應列入中長期五年計畫"}, {"key": "B", "text": "應列入年度計畫"}, {"key": "C", "text": "隨時依理事長口頭交辦執行"}, {"key": "D", "text": "經會員大會決議後免作計畫"}], "correctAnswers": ["B"], "explanation": "依農會法第4條第3項規定：「農會辦理第一項任務，應列入年度計畫。」"},
    {"id": "s10", "type": "single", "chapter": "任務", "article": "農會法第5條", "question": "各級農會為辦理事業，經主管機關核准得組織共同經營機構，該共同經營機構之法人資格為何？", "options": [{"key": "A", "text": "非法人團體"}, {"key": "B", "text": "法人"}, {"key": "C", "text": "合夥"}, {"key": "D", "text": "信託基金"}], "correctAnswers": ["B"], "explanation": "依農會法第5條第1項：共同經營機構為法人，其組織經營辦法，由中央主管機關定之。"},
    {"id": "s11", "type": "single", "chapter": "任務", "article": "農會法第5條", "question": "農會辦理會員金融事業，應設立何種內部部門？", "options": [{"key": "A", "text": "儲蓄部"}, {"key": "B", "text": "信用部"}, {"key": "C", "text": "信託部"}, {"key": "D", "text": "融資部"}], "correctAnswers": ["B"], "explanation": "依農會法第5條第2項：農會辦理會員金融事業，應設立信用部，除本法另有規定者外，由中央目的事業主管機關依銀行法相關規定管理之。"},
    {"id": "s12", "type": "single", "chapter": "任務", "article": "農會法第5條", "question": "農會信用部業務之輔導及資金融通，由下列何者負責辦理？", "options": [{"key": "A", "text": "中央銀行"}, {"key": "B", "text": "農業行庫"}, {"key": "C", "text": "金融監督管理委員會"}, {"key": "D", "text": "財政部"}], "correctAnswers": ["B"], "explanation": "依農會法第5條第5項：農會信用部業務之輔導及資金之融通，由農業行庫負責辦理。"},
    {"id": "s13", "type": "single", "chapter": "任務", "article": "農會法第5條", "question": "各級農會共同投資組織股份有限公司，至少須由多少個以上之農會共同發起？", "options": [{"key": "A", "text": "二個以上"}, {"key": "B", "text": "三個以上"}, {"key": "C", "text": "五個以上"}, {"key": "D", "text": "十個以上"}], "correctAnswers": ["C"], "explanation": "依農會法第5條第8項：各級農會為辦理前條事業，得由五個以上農會共同投資組織股份有限公司。"},
    {"id": "s14", "type": "single", "chapter": "任務", "article": "農會法施行細則第5條", "question": "農會辦理農畜產品加工或資材製造業務，得設立何種附屬機構？", "options": [{"key": "A", "text": "加工廠或製造廠"}, {"key": "B", "text": "研發中心"}, {"key": "C", "text": "檢驗實驗室"}, {"key": "D", "text": "展覽館"}], "correctAnswers": ["A"], "explanation": "依農會法施行細則第5條：農會辦理本法第四條第一項第八款之農畜產品加工、製造及第九款之農業生產資材加工、製造業務，得設立各類加工廠或製造廠。"},
    {"id": "s15", "type": "single", "chapter": "任務", "article": "農會法施行細則第6條", "question": "農會辦理農業生產資材配售及會員生活用品供銷業務，得設立何種單位？", "options": [{"key": "A", "text": "展售會"}, {"key": "B", "text": "門市部"}, {"key": "C", "text": "物流轉運站"}, {"key": "D", "text": "加油站"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第6條：農會辦理本法第四條第一項第九款之農業生產資材配售及會員生活用品供銷業務，得設立門市部。"},
    {"id": "s16", "type": "single", "chapter": "任務", "article": "農會法施行細則第8條", "question": "農會辦理農業旅遊及農村休閒事業，得設立何種附屬部門？", "options": [{"key": "A", "text": "旅行社"}, {"key": "B", "text": "農業休閒旅遊部門"}, {"key": "C", "text": "大飯店"}, {"key": "D", "text": "遊樂園"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第8條：農會辦理本法第四條第一項第二十款之農業旅遊及農村休閒事業，得設立農業休閒旅遊部門。"},
    {"id": "s17", "type": "single", "chapter": "任務", "article": "農會法施行細則第10條", "question": "依農會法施行細則第十條規定，農會對會員之服務範圍為何？", "options": [{"key": "A", "text": "僅限會員本人"}, {"key": "B", "text": "包括其同戶家屬"}, {"key": "C", "text": "包括其所有親戚"}, {"key": "D", "text": "包括全村所有居民"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第10條：農會對會員之服務，得包括其同戶家屬。"},

    # 設立及合併
    {"id": "s18", "type": "single", "chapter": "設立及合併", "article": "農會法第6條", "question": "農會組織層級依農會法第六條劃分，共分為幾級？", "options": [{"key": "A", "text": "二級"}, {"key": "B", "text": "三級"}, {"key": "C", "text": "四級"}, {"key": "D", "text": "五級"}], "correctAnswers": ["B"], "explanation": "依農會法第6條第1項：農會分為下列三級：一、鄉（鎮、市、區）農會。二、縣（市）農會及直轄市農會。三、全國農會。"},
    {"id": "s19", "type": "single", "chapter": "設立及合併", "article": "農會法第6-1條", "question": "鄉、鎮（市）、區以下按實際需要劃設之農事小組，其性質為何？", "options": [{"key": "A", "text": "獨立法人機構"}, {"key": "B", "text": "農會事業基層推行單位"}, {"key": "C", "text": "行政機關分支單位"}, {"key": "D", "text": "司法仲裁單位"}], "correctAnswers": ["B"], "explanation": "依農會法第6條之1：鄉、鎮（市）、區以下按實際需要，劃設農事小組，為農會事業基層推行單位。"},
    {"id": "s20", "type": "single", "chapter": "設立及合併", "article": "農會法施行細則第11條", "question": "鄉（鎮、市、區）農會劃設之農事小組，原則上戶數與區域劃設限制為何？", "options": [{"key": "A", "text": "以每一鄰一個小組為限"}, {"key": "B", "text": "以每一村里一個小組為限"}, {"key": "C", "text": "以每五十戶一個小組為限"}, {"key": "D", "text": "無區域限制自由劃設"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第11條第3項：本法第六條之一所定鄉（鎮、市、區）農會劃設之農事小組，以每一村里一個小組為限。"},
    {"id": "s21", "type": "single", "chapter": "設立及合併", "article": "農會法施行細則第11條", "question": "農事小組會員人數除贊助會員外，未滿多少人者得合併鄰近村里劃設小組？", "options": [{"key": "A", "text": "二十人"}, {"key": "B", "text": "三十人"}, {"key": "C", "text": "五十人"}, {"key": "D", "text": "一百人"}], "correctAnswers": ["C"], "explanation": "依農會法施行細則第11條第3項：其會員人數除贊助會員外，未滿五十人者，得由農會按照會員分布、地理環境及村里區域等情況合併鄰近之村里設一小組。"},
    {"id": "s22", "type": "single", "chapter": "設立及合併", "article": "農會法施行細則第11條", "question": "農事小組劃設後，因會員人數增減得重新劃設，但在農會改選前多久時間內「不得為之」？", "options": [{"key": "A", "text": "二個月內"}, {"key": "B", "text": "三個月內"}, {"key": "C", "text": "六個月內"}, {"key": "D", "text": "一年內"}], "correctAnswers": ["C"], "explanation": "依農會法施行細則第11條第4項：但農會改選前六個月內不得為之。"},
    {"id": "s23", "type": "single", "chapter": "設立及合併", "article": "農會法第7條", "question": "各級農會以何者為其組織區域，並冠以各該區域之名稱？", "options": [{"key": "A", "text": "灌溉區域"}, {"key": "B", "text": "行政區域"}, {"key": "C", "text": "郵遞區號區域"}, {"key": "D", "text": "選舉區域"}], "correctAnswers": ["B"], "explanation": "依農會法第7條第1項：各級農會以行政區域為其組織區域，並冠以各該區域之名稱。同一區域內以組織一個農會為原則。"},
    {"id": "s24", "type": "single", "chapter": "設立及合併", "article": "農會法第8條", "question": "鄉（鎮、市、區）內具有農會會員資格滿多少人時，得發起組織基層農會？", "options": [{"key": "A", "text": "三十人"}, {"key": "B", "text": "五十人"}, {"key": "C", "text": "一百人"}, {"key": "D", "text": "二百人"}], "correctAnswers": ["B"], "explanation": "依農會法第8條第1項：鄉（鎮、市、區）內具有農會會員資格滿五十人時，得發起組織基層農會。"},
    {"id": "s25", "type": "single", "chapter": "設立及合併", "article": "農會法第8條", "question": "鄉（鎮、市、區）農會成立多少個以上，得組織上級農會？", "options": [{"key": "A", "text": "二個以上"}, {"key": "B", "text": "三個以上"}, {"key": "C", "text": "五個以上"}, {"key": "D", "text": "十個以上"}], "correctAnswers": ["B"], "explanation": "依農會法第8條第2項：鄉（鎮、市、區）農會成立三個以上或經中央主管機關之核准，得組織上級農會。"},
    {"id": "s26", "type": "single", "chapter": "設立及合併", "article": "農會法第9條", "question": "農會之發起組織，應報經何者許可後，方得召開發起人會議？", "options": [{"key": "A", "text": "主管機關"}, {"key": "B", "text": "地方法院"}, {"key": "C", "text": "上級農會理事長"}, {"key": "D", "text": "警察機關"}], "correctAnswers": ["A"], "explanation": "依農會法第9條第1項：農會之發起組織，應報經主管機關許可後，方得召開發起人會議，並推定籌備員，組織籌備會。"},
    {"id": "s27", "type": "single", "chapter": "設立及合併", "article": "農會法第10條", "question": "農會應於成立大會後多久時間內，將章程、名冊等報請主管機關核發登記證書？", "options": [{"key": "A", "text": "三日內"}, {"key": "B", "text": "七日內"}, {"key": "C", "text": "十五日內"}, {"key": "D", "text": "三十日內"}], "correctAnswers": ["B"], "explanation": "依農會法第10條：農會應於成立大會後七日內，將章程、會員（代表）名冊及理、監事簡歷冊，報請主管機關核發登記證書及圖記。"},
    {"id": "s28", "type": "single", "chapter": "設立及合併", "article": "農會法第11-1條", "question": "農會辦理合併後，應自主管機關核准合併之日起多久時間內，完成選任人員改選及總幹事改聘？", "options": [{"key": "A", "text": "三個月內"}, {"key": "B", "text": "六個月內"}, {"key": "C", "text": "一年內"}, {"key": "D", "text": "二年內"}], "correctAnswers": ["B"], "explanation": "依農會法第11條之1第2項：農會應自前項直轄市或縣（市）主管機關核准合併之日起六個月內，完成選任人員改選及總幹事改聘。"},
    {"id": "s29", "type": "single", "chapter": "設立及合併", "article": "農會法第11-2條", "question": "農會合併公告及通知債權人，應指定多久以上之期間為異議期間？", "options": [{"key": "A", "text": "十日以上"}, {"key": "B", "text": "十五日以上"}, {"key": "C", "text": "三十日以上"}, {"key": "D", "text": "六十日以上"}], "correctAnswers": ["C"], "explanation": "依農會法第11條之2第3項及第4項：應指定三十日以上之期間為異議期間。"},
    {"id": "s30", "type": "single", "chapter": "設立及合併", "article": "農會法第11-2條", "question": "農會合併決議，不同意合併之會員聲明異議達全體會員多少比例以上時，原決議失效？", "options": [{"key": "A", "text": "四分之一以上"}, {"key": "B", "text": "三分之一以上"}, {"key": "C", "text": "二分之一以上"}, {"key": "D", "text": "三分之二以上"}], "correctAnswers": ["B"], "explanation": "依農會法第11條之2第3項：異議之會員達全體會員三分之一以上時，原決議失效。"},
    {"id": "s31", "type": "single", "chapter": "設立及合併", "article": "農會法第11-6條", "question": "合併後農會因合併產生之商譽，於申報所得稅時，得於多久年限內攤銷？", "options": [{"key": "A", "text": "五年內"}, {"key": "B", "text": "十年內"}, {"key": "C", "text": "十五年內"}, {"key": "D", "text": "二十年內"}], "correctAnswers": ["C"], "explanation": "依農會法第11條之6第1項第5款：因合併產生商譽，於申報所得稅時，得於十五年內攤銷之。"},
    {"id": "s32", "type": "single", "chapter": "設立及合併", "article": "農會法第11-6條", "question": "合併後農會因合併產生之費用，於申報所得稅時，得於多久年限內認列？", "options": [{"key": "A", "text": "五年內"}, {"key": "B", "text": "十年內"}, {"key": "C", "text": "十五年內"}, {"key": "D", "text": "二十年內"}], "correctAnswers": ["B"], "explanation": "依農會法第11條之6第1項第6款：因合併產生之費用，於申報所得稅時，得於十年內認列。"},

    # 會員
    {"id": "s33", "type": "single", "chapter": "會員", "article": "農會法第12條", "question": "依農會法第十二條規定，申請加入基層農會為會員者，其國籍與年齡限制為何？", "options": [{"key": "A", "text": "外國籍年滿十八歲"}, {"key": "B", "text": "凡成年之中華民國國民"}, {"key": "C", "text": "年滿十六歲之國民"}, {"key": "D", "text": "無年齡限制"}], "correctAnswers": ["B"], "explanation": "依農會法第12條第1項：凡成年之中華民國國民，設籍農會組織區域內，實際從事農業，合於規定者得加入為會員。"},
    {"id": "s34", "type": "single", "chapter": "會員", "article": "農會法第14條", "question": "關於農會會員之戶數限制，下列敘述何者正確？", "options": [{"key": "A", "text": "每戶得有二人入會"}, {"key": "B", "text": "農會會員每戶以一人為限"}, {"key": "C", "text": "無戶數限制，凡從農者皆可入會"}, {"key": "D", "text": "每一農地單位限一人"}], "correctAnswers": ["B"], "explanation": "依農會法第14條規定：「農會會員每戶以一人為限。」"},
    {"id": "s35", "type": "single", "chapter": "會員", "article": "農會法施行細則第17條", "question": "農會法第十四條所稱之「戶」，係以下列何者為準？", "options": [{"key": "A", "text": "戶長登記"}, {"key": "B", "text": "戶籍登記"}, {"key": "C", "text": "土地登記地號"}, {"key": "D", "text": "稅務申報戶"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第17條：本法第十四條所稱之戶，以戶籍登記為準。入會會員不限於戶長。"},
    {"id": "s36", "type": "single", "chapter": "會員", "article": "農會法第12條", "question": "農會會員入會未滿多久者，無農會法所定之選舉權及被選舉權？", "options": [{"key": "A", "text": "三個月"}, {"key": "B", "text": "六個月"}, {"key": "C", "text": "一年"}, {"key": "D", "text": "二年"}], "correctAnswers": ["B"], "explanation": "依農會法第12條第4項：「農會會員入會未滿六個月者，無本法所定選舉權及被選舉權。」"},
    {"id": "s37", "type": "single", "chapter": "會員", "article": "農會法第13條", "question": "個人贊助會員或團體贊助會員，除得當選何種職務外，無選舉權及其他被選舉權？", "options": [{"key": "A", "text": "理事"}, {"key": "B", "text": "理事長"}, {"key": "C", "text": "監事"}, {"key": "D", "text": "總幹事"}], "correctAnswers": ["C"], "explanation": "依農會法第13條第3項：個人贊助會員及團體贊助會員，除得當選監事外，無選舉權及其他被選舉權。"},
    {"id": "s38", "type": "single", "chapter": "會員", "article": "農會法施行細則第16條", "question": "農會法第十三條第二項團體贊助會員，係以何人為代表出席？", "options": [{"key": "A", "text": "全體股東"}, {"key": "B", "text": "各該團體之法定代理人"}, {"key": "C", "text": "由主管機關指定人員"}, {"key": "D", "text": "工會理事長"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第16條：本法第十三條第二項團體贊助會員，以各該團體之法定代理人為代表人。"},
    {"id": "s39", "type": "single", "chapter": "會員", "article": "農會法第15條", "question": "各級農會會員代表中，自耕農、佃農及雇農合計應占多少比例以上？", "options": [{"key": "A", "text": "二分之一以上"}, {"key": "B", "text": "三分之二以上"}, {"key": "C", "text": "四分之三以上"}, {"key": "D", "text": "五分之四以上"}], "correctAnswers": ["B"], "explanation": "依農會法第15條第2項：各級農會會員代表中，應有三分之二以上為自耕農、佃農及雇農。"},
    {"id": "s40", "type": "single", "chapter": "會員", "article": "農會法第15條", "question": "農會會員代表之任期為幾年？", "options": [{"key": "A", "text": "二年"}, {"key": "B", "text": "三年"}, {"key": "C", "text": "四年"}, {"key": "D", "text": "五年"}], "correctAnswers": ["C"], "explanation": "依農會法第15條第3項：會員代表任期為四年，連選得連任。"},
    {"id": "s41", "type": "single", "chapter": "會員", "article": "農會法第15條", "question": "農會會員代表不得兼任下列何種職務？", "options": [{"key": "A", "text": "農事小組組長、副組長及農會聘、雇人員"}, {"key": "B", "text": "村里長"}, {"key": "C", "text": "社區發展協會理事"}, {"key": "D", "text": "寺廟管理委員會委員"}], "correctAnswers": ["A"], "explanation": "依農會法第15條第4項：會員代表不得兼任農事小組組長、副組長及農會聘、雇人員。"},
    {"id": "s42", "type": "single", "chapter": "會員", "article": "農會法施行細則第18條", "question": "鄉（鎮、市、區）農會參加縣（市）農會之會員代表名額，會員總數在二千人以下者選出二人，超過二千人時，每滿多少人加選一人？", "options": [{"key": "A", "text": "五百人"}, {"key": "B", "text": "一千人"}, {"key": "C", "text": "二千人"}, {"key": "D", "text": "三千人"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第18條第1項第1款：按會員總數在基本數額二千人以下者，選出二人，超過二千人時，每滿一千人加選一人。"},
    {"id": "s43", "type": "single", "chapter": "會員", "article": "農會法施行細則第18條", "question": "縣（市）農會參加省農會之會員代表名額，最高不得超過多少人，最低不得少於多少人？", "options": [{"key": "A", "text": "最高90人，最低50人"}, {"key": "B", "text": "最高65人，最低31人"}, {"key": "C", "text": "最高45人，最低21人"}, {"key": "D", "text": "最高30人，最低15人"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第18條第3項：最高不得超過六十五人，最低不得少於三十一人。"},
    {"id": "s44", "type": "single", "chapter": "會員", "article": "農會法第15-1條", "question": "農會會員登記為會員代表候選人，其入會須滿多久時間以上？", "options": [{"key": "A", "text": "三個月以上"}, {"key": "B", "text": "六個月以上"}, {"key": "C", "text": "一年以上"}, {"key": "D", "text": "二年以上"}], "correctAnswers": ["B"], "explanation": "依農會法第15條之1第1項：農會會員入會滿六個月以上者，得登記為會員代表候選人。"},
    {"id": "s45", "type": "single", "chapter": "會員", "article": "農會法第16條", "question": "下列何者「非」農會法第十六條規定不得為農會會員之情形？", "options": [{"key": "A", "text": "受破產之宣告尚未復權者"}, {"key": "B", "text": "受監護宣告尚未撤銷者"}, {"key": "C", "text": "曾受本法所定除名處分者"}, {"key": "D", "text": "年滿七十歲之自耕農"}], "correctAnswers": ["D"], "explanation": "依農會法第16條，年滿70歲之自耕農若合於規定仍得為會員。A、B、C皆為消極限制。"},
    {"id": "s46", "type": "single", "chapter": "會員", "article": "農會法第18條", "question": "下列何者「非」農會法第十八條所定會員之「出會」原因？", "options": [{"key": "A", "text": "死亡"}, {"key": "B", "text": "喪失中華民國國籍者"}, {"key": "C", "text": "住址遷離原農會組織區域者"}, {"key": "D", "text": "出國旅遊超過一個月者"}], "correctAnswers": ["D"], "explanation": "依農會法第18條，出國旅遊非出會原因。出會原因包含：死亡、受破產/監護宣告、喪失國籍、住址遷離區域、除名。"},

    # 職員
    {"id": "s47", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "鄉（鎮、市、區）農會之理事名額規定為何？", "options": [{"key": "A", "text": "七人"}, {"key": "B", "text": "九人"}, {"key": "C", "text": "九人至十五人"}, {"key": "D", "text": "十五人"}], "correctAnswers": ["B"], "explanation": "依農會法第19條第1項第1款規定：鄉（鎮、市、區）農會理事九人。"},
    {"id": "s48", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "縣（市）農會之理事名額規定為何？", "options": [{"key": "A", "text": "九人"}, {"key": "B", "text": "九人至十五人"}, {"key": "C", "text": "十五人至二十一人"}, {"key": "D", "text": "二十一人至二十七人"}], "correctAnswers": ["B"], "explanation": "依農會法第19條第1項第2款：縣（市）農會理事九人至十五人。"},
    {"id": "s49", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "全國農會之理事名額規定為何？", "options": [{"key": "A", "text": "九人至十五人"}, {"key": "B", "text": "十五人至二十一人"}, {"key": "C", "text": "二十一人至二十七人"}, {"key": "D", "text": "三十一人"}], "correctAnswers": ["C"], "explanation": "依農會法第19條第1項第4款：全國農會理事二十一人至二十七人。"},
    {"id": "s50", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "農會監事名額，依法不得超過其理事名額之多少比例？", "options": [{"key": "A", "text": "二分之一"}, {"key": "B", "text": "三分之一"}, {"key": "C", "text": "四分之一"}, {"key": "D", "text": "五分之一"}], "correctAnswers": ["B"], "explanation": "依農會法第19條第1項第5款：農會監事名額為其理事名額三分之一。"},
    {"id": "s51", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "農會候補理、監事名額，不得超過所置理、監事名額之多少比例？", "options": [{"key": "A", "text": "三分之一"}, {"key": "B", "text": "二分之一"}, {"key": "C", "text": "三分之二"}, {"key": "D", "text": "等額"}], "correctAnswers": ["B"], "explanation": "依農會法第19條第1項第6款：農會置候補理、監事，其名額不得超過所置理、監事名額二分之一。"},
    {"id": "s52", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "各級農會理、監事中，應有多少比例以上為自耕農、佃農或雇農？", "options": [{"key": "A", "text": "二分之一以上"}, {"key": "B", "text": "三分之二以上"}, {"key": "C", "text": "四分之三以上"}, {"key": "D", "text": "全部"}], "correctAnswers": ["B"], "explanation": "依農會法第19條第2項：各級農會理、監事，其中應有三分之二以上為自耕農、佃農或雇農。"},
    {"id": "s53", "type": "single", "chapter": "職員", "article": "農會法第19條", "question": "農會理事長與常務監事係如何產生？", "options": [{"key": "A", "text": "由主管機關直接派任"}, {"key": "B", "text": "由會員大會直接投票選舉"}, {"key": "C", "text": "由理、監事分別互選一人"}, {"key": "D", "text": "由總幹事提名經大會同意"}], "correctAnswers": ["C"], "explanation": "依農會法第19條第3項：農會理、監事應分別互選一人為理事長與常務監事。"},
    {"id": "s54", "type": "single", "chapter": "職員", "article": "農會法第20條", "question": "基層農會理事、監事之候選人資格限制為何？", "options": [{"key": "A", "text": "以其所屬基層農會會員為限"}, {"key": "B", "text": "不限於農會會員"}, {"key": "C", "text": "須具備大專以上學歷"}, {"key": "D", "text": "須曾任公務員"}], "correctAnswers": ["A"], "explanation": "依農會法第20條第1項：農會理、監事之候選人，以其所屬基層農會會員為限。"},
    {"id": "s55", "type": "single", "chapter": "職員", "article": "農會法第20-1條", "question": "登記為農會理事、監事候選人者，其入會須滿多少時間以上？", "options": [{"key": "A", "text": "六個月以上"}, {"key": "B", "text": "一年以上"}, {"key": "C", "text": "二年以上"}, {"key": "D", "text": "三年以上"}], "correctAnswers": ["C"], "explanation": "依農會法第20條之1第1項第1款：農會會員入會滿二年以上者，得登記為農會理事、監事候選人。"},
    {"id": "s56", "type": "single", "chapter": "職員", "article": "農會法第21條", "question": "關於農會理、監事之薪給待遇規定為何？", "options": [{"key": "A", "text": "比照薦任公務員給薪"}, {"key": "B", "text": "均為無給職"}, {"key": "C", "text": "由理事會自由訂定月薪"}, {"key": "D", "text": "按出席天數發給每日五千元工資"}], "correctAnswers": ["B"], "explanation": "依農會法第21條規定：「農會理、監事均為無給職...」"},
    {"id": "s57", "type": "single", "chapter": "職員", "article": "農會法第22條", "question": "農會理事、監事任期均為四年，連選得連任一次。但連任人數不得超過理、監事名額之多少？", "options": [{"key": "A", "text": "三分之一"}, {"key": "B", "text": "二分之一"}, {"key": "C", "text": "三分之二"}, {"key": "D", "text": "無人數限制"}], "correctAnswers": ["B"], "explanation": "依農會法第22條第1項：農會理、監事任期均為四年，連選得連任一次。但連任人數不得超過理、監事名額二分之一。"},
    {"id": "s58", "type": "single", "chapter": "職員", "article": "農會法第22-1條", "question": "農會選任人員應於任期屆滿多久時間前或主管機關指定之日期完成改選？", "options": [{"key": "A", "text": "十日前"}, {"key": "B", "text": "十五日前"}, {"key": "C", "text": "三十日前"}, {"key": "D", "text": "六十日前"}], "correctAnswers": ["C"], "explanation": "依農會法第22條之1第1項：農會選任人員應於任期屆滿三十日前或主管機關指定之日期完成改選。"},
    {"id": "s59", "type": "single", "chapter": "職員", "article": "農會法施行細則第20條", "question": "農會理事、監事出缺時，應於出缺日起多久時間內由候補人依次遞補？", "options": [{"key": "A", "text": "十日內"}, {"key": "B", "text": "十五日內"}, {"key": "C", "text": "三十日內"}, {"key": "D", "text": "六十日內"}], "correctAnswers": ["C"], "explanation": "依農會法施行細則第20條第1項：農會理事、監事出缺，應於出缺日起三十日內由候補理事、監事依次遞補。"},
    {"id": "s60", "type": "single", "chapter": "職員", "article": "農會法第23條", "question": "農事小組置組長、副組長各一人，由會員選任之，其任期為幾年？", "options": [{"key": "A", "text": "二年"}, {"key": "B", "text": "三年"}, {"key": "C", "text": "四年"}, {"key": "D", "text": "五年"}], "correctAnswers": ["C"], "explanation": "依農會法第23條第1項：農事小組置組長、副組長各一人，由會員選任之，任期四年，連選得連任。"},
    {"id": "s61", "type": "single", "chapter": "職員", "article": "農會法第23-1條", "question": "農會二種以上選任人員選舉同時辦理時，申請登記為候選人者，以登記幾種為限？", "options": [{"key": "A", "text": "一種為限"}, {"key": "B", "text": "二種為限"}, {"key": "C", "text": "三種為限"}, {"key": "D", "text": "無限制"}], "correctAnswers": ["A"], "explanation": "依農會法第23條之1第1項：農會二種以上選任人員選舉同時辦理時，申請登記為候選人者，以登記一種為限。同時為二種以上候選人登記時，其登記無效。"},
    {"id": "s62", "type": "single", "chapter": "職員", "article": "農會法第25條", "question": "農會總幹事係由何者聘任之？", "options": [{"key": "A", "text": "會員大會"}, {"key": "B", "text": "理事會"}, {"key": "C", "text": "監事會"}, {"key": "D", "text": "中央主管機關"}], "correctAnswers": ["B"], "explanation": "依農會法第25條第1項：農會置總幹事一人，由理事會就中央或直轄市主管機關遴選之合格人員中聘任之。"},
    {"id": "s63", "type": "single", "chapter": "職員", "article": "農會法第25條", "question": "農會總幹事之聘任，應於理事會成立後多久時間內為之？", "options": [{"key": "A", "text": "三十日內"}, {"key": "B", "text": "六十日內"}, {"key": "C", "text": "九十日內"}, {"key": "D", "text": "四十五日內"}], "correctAnswers": ["B"], "explanation": "依農會法第25條第2項：總幹事之聘任，應於理事會成立後六十日內為之。"},
    {"id": "s64", "type": "single", "chapter": "職員", "article": "農會法第25條", "question": "農會總幹事之聘任與解聘決議門檻為何？", "options": [{"key": "A", "text": "聘任須出席1/2，解聘須出席2/3"}, {"key": "B", "text": "聘任須全體理事1/2以上，解聘須全體理事2/3以上"}, {"key": "C", "text": "聘任與解聘皆須全體理事2/3以上"}, {"key": "D", "text": "聘任與解聘皆須出席理事2/3以上"}], "correctAnswers": ["B"], "explanation": "依農會法第25條第3項：農會總幹事之聘任，須經全體理事二分之一以上之決議行之；其解聘須經全體理事三分之二以上之決議行之。"},
    {"id": "s65", "type": "single", "chapter": "職員", "article": "農會法第25-1條", "question": "各級農會新進總幹事之年齡上限為何？", "options": [{"key": "A", "text": "四十五歲"}, {"key": "B", "text": "五十歲"}, {"key": "C", "text": "五十五歲"}, {"key": "D", "text": "六十歲"}], "correctAnswers": ["C"], "explanation": "依農會法第25條之1第1項第3款：各級農會新進總幹事之年齡，不得超過五十五歲。"},
    {"id": "s66", "type": "single", "chapter": "職員", "article": "農會法第25-3條", "question": "農會總幹事應於受聘之日起多久時間內，檢具保證書向農會保證？", "options": [{"key": "A", "text": "七日內"}, {"key": "B", "text": "十日內"}, {"key": "C", "text": "十五日內"}, {"key": "D", "text": "三十日內"}], "correctAnswers": ["B"], "explanation": "依農會法第25條之3第1項：農會總幹事應於受聘之日起十日內，檢具有不動產之保證人兩人以上保證書或員工誠實保險，向農會保證。"},
    {"id": "s67", "type": "single", "chapter": "職員", "article": "農會法第26條", "question": "農會總幹事以外之聘任職員，係由何者聘任並指揮監督？", "options": [{"key": "A", "text": "理事長"}, {"key": "B", "text": "常務監事"}, {"key": "C", "text": "總幹事"}, {"key": "D", "text": "主管機關首長"}], "correctAnswers": ["C"], "explanation": "依農會法第26條第1項：農會總幹事以外之聘任職員，由總幹事就農會統一考試合格人員中聘任並指揮、監督。"},
    {"id": "s68", "type": "single", "chapter": "職員", "article": "農會法第27條", "question": "農會總幹事及聘雇人員之兼職限制為何？", "options": [{"key": "A", "text": "均為專任，不得兼營工商業或兼任任何有給職務"}, {"key": "B", "text": "得兼任民意代表"}, {"key": "C", "text": "得兼任私立學校董事長"}, {"key": "D", "text": "無限制"}], "correctAnswers": ["A"], "explanation": "依農會法第27條：農會總幹事及聘雇人員均為專任，不得兼營工商業或兼任公私團體任何有給職務或各級民意代表。如有競選公職，一經當選就職，視同辭職。"},
    {"id": "s69", "type": "single", "chapter": "職員", "article": "農會法第27-1條", "question": "下列哪一種親屬關係者，「不得」同時擔任同一農會之理事長、常務監事或總幹事？", "options": [{"key": "A", "text": "三親等以內血親"}, {"key": "B", "text": "配偶、二親等以內血親或一親等姻親"}, {"key": "C", "text": "四親等以內血親"}, {"key": "D", "text": "二親等以內姻親"}], "correctAnswers": ["B"], "explanation": "依農會法第27條之1第1項：具有配偶、二親等以內之血親或一親等姻親關係者，不得同時擔任同一農會之理事長、常務監事或總幹事。"},

    # 權責劃分
    {"id": "s70", "type": "single", "chapter": "權責劃分", "article": "農會法第28條", "question": "農會之最高權力機構為何？", "options": [{"key": "A", "text": "理事會"}, {"key": "B", "text": "監事會"}, {"key": "C", "text": "會員（代表）大會"}, {"key": "D", "text": "主管機關"}], "correctAnswers": ["C"], "explanation": "依農會法第28條規定：農會以會員（代表）大會為最高權力機構。"},
    {"id": "s71", "type": "single", "chapter": "權責劃分", "article": "農會法第28條", "question": "會員（代表）大會休會期間，負責策劃業務之機構為何？", "options": [{"key": "A", "text": "理事會"}, {"key": "B", "text": "監事會"}, {"key": "C", "text": "會務部"}, {"key": "D", "text": "農業部"}], "correctAnswers": ["A"], "explanation": "依農會法第28條：會員（代表）大會休會期間，理事會依會員（代表）大會之決議策劃業務。"},
    {"id": "s72", "type": "single", "chapter": "權責劃分", "article": "農會法第28條", "question": "負責監察農會業務及財務之機構為何？", "options": [{"key": "A", "text": "理事會"}, {"key": "B", "text": "監事會"}, {"key": "C", "text": "稽核室"}, {"key": "D", "text": "審計部"}], "correctAnswers": ["B"], "explanation": "依農會法第28條：監事會監察業務及財務。"},
    {"id": "s73", "type": "single", "chapter": "權責劃分", "article": "農會法第29條", "question": "農會會員（代表）、理事、監事行使職權之時間限制為何？", "options": [{"key": "A", "text": "應限於會議時為之"}, {"key": "B", "text": "隨時皆得獨立行使"}, {"key": "C", "text": "僅限於辦公時間內"}, {"key": "D", "text": "經理事長書面授權時"}], "correctAnswers": ["A"], "explanation": "依農會法第29條規定：農會會員（代表）、理事、監事之行使職權，應限於會議時為之。"},
    {"id": "s74", "type": "single", "chapter": "權責劃分", "article": "農會法第30條", "question": "農會會議決議有違反法令致損害農會時，出席會議人員之責任為何？", "options": [{"key": "A", "text": "由理事長一人負全部責任"}, {"key": "B", "text": "出席人員應負賠償責任，但表決時提出異議經紀錄記明者免責"}, {"key": "C", "text": "全部出席人員一律免責"}, {"key": "D", "text": "由總幹事代為負擔賠償"}], "correctAnswers": ["B"], "explanation": "依農會法第30條第1項：其決議有違反法令或章程，致損害農會時，應負賠償責任。但表決時提出異議，經會議紀錄記明者，免其責任。"},
    {"id": "s75", "type": "single", "chapter": "權責劃分", "article": "農會法第30條", "question": "農會會議對重大事件之表決，應採用何種方式？", "options": [{"key": "A", "text": "舉手表決"}, {"key": "B", "text": "無記名投票"}, {"key": "C", "text": "書面記名行之"}, {"key": "D", "text": "鼓掌通過"}], "correctAnswers": ["C"], "explanation": "依農會法第30條第2項：農會會議對重大事件之表決，應以書面記名行之。"},
    {"id": "s76", "type": "single", "chapter": "權責劃分", "article": "農會法第31條", "question": "農會總幹事之權責與地位關係為何？", "options": [{"key": "A", "text": "秉承監事會決議執行任務"}, {"key": "B", "text": "秉承理事會決議執行任務，向理事會負責"}, {"key": "C", "text": "獨立行使職權，不受理事會監督"}, {"key": "D", "text": "直接向主管機關負責"}], "correctAnswers": ["B"], "explanation": "依農會法第31條規定：農會總幹事秉承理事會決議執行任務，向理事會負責。"},
    {"id": "s77", "type": "single", "chapter": "權責劃分", "article": "農會法第37條", "question": "農會會員（代表）大會對於章程之修改或財產之處分，須經何種特別決議門檻？", "options": [{"key": "A", "text": "全體過半數出席，出席過半數同意"}, {"key": "B", "text": "全體三分之二以上出席，出席三分之二以上決議"}, {"key": "C", "text": "全體四分之三以上出席，出席三分之二以上決議"}, {"key": "D", "text": "全體出席，全體一致決議"}], "correctAnswers": ["B"], "explanation": "依農會法第37條：農會會員（代表）大會對章程變更、財產處分等事項，須經全體會員（代表）三分之二以上之出席，及出席人三分之二以上之決議行之。"},

    # 會議
    {"id": "s78", "type": "single", "chapter": "會議", "article": "農會法第33條", "question": "各級農會會員（代表）大會之「定期會議」，每年應召集幾次？", "options": [{"key": "A", "text": "一次"}, {"key": "B", "text": "二次"}, {"key": "C", "text": "三次"}, {"key": "D", "text": "四次"}], "correctAnswers": ["A"], "explanation": "依農會法第33條第2項：定期會議，各級農會每年應召集一次。"},
    {"id": "s79", "type": "single", "chapter": "會議", "article": "農會法第33條", "question": "會員（代表）大會臨時會議，經會員（代表）多少比例以上請求時得召集之？", "options": [{"key": "A", "text": "五分之一以上"}, {"key": "B", "text": "四分之一以上"}, {"key": "C", "text": "三分之一以上"}, {"key": "D", "text": "二分之一以上"}], "correctAnswers": ["C"], "explanation": "依農會法第33條第2項：臨時會議，經會員（代表）三分之一以上請求，或理事會認為必要時召集之。"},
    {"id": "s80", "type": "single", "chapter": "會議", "article": "農會法第34條", "question": "農會理事會議與監事會議之召集人分別為何？", "options": [{"key": "A", "text": "理事會議由理事長召集，監事會議由常務監事召集"}, {"key": "B", "text": "均由總幹事召集"}, {"key": "C", "text": "均由主管機關指派人員召集"}, {"key": "D", "text": "理事會議由總幹事召集，監事會議由理事長召集"}], "correctAnswers": ["A"], "explanation": "依農會法第34條：農會理事會議由理事長召集，監事會議由常務監事召集，並各為會議之主席。"},
    {"id": "s81", "type": "single", "chapter": "會議", "article": "農會法第35條", "question": "農事小組會議每年至少應舉行幾次？", "options": [{"key": "A", "text": "至少一次"}, {"key": "B", "text": "至少二次"}, {"key": "C", "text": "至少四次"}, {"key": "D", "text": "無限制"}], "correctAnswers": ["A"], "explanation": "依農會法第35條：農事小組應舉行小組會議，每年至少一次，由組長召集，並為會議之主席。"},
    {"id": "s82", "type": "single", "chapter": "會議", "article": "農會法第36條", "question": "農會法定會議原則上開會與決議門檻為何？", "options": [{"key": "A", "text": "須有出席1/3，同意1/2"}, {"key": "B", "text": "須有應出席人數2/1以上之出席，及出席人數1/2以上之同意"}, {"key": "C", "text": "須有應出席人數2/3以上之出席，及出席人數2/3以上之同意"}, {"key": "D", "text": "無門檻限制"}], "correctAnswers": ["B"], "explanation": "依農會法第36條第1項：須有各該會議應出席人數二分之一以上之出席，方得開會，及出席人數二分之一以上之同意，方得決議。"},
    {"id": "s83", "type": "single", "chapter": "會議", "article": "農會法第36條", "question": "除聘任總幹事外，會議經二次召集均未達1/2出席時，第三次召集出席人數達多少即可開會？", "options": [{"key": "A", "text": "四分之一以上"}, {"key": "B", "text": "三分之一以上"}, {"key": "C", "text": "五分之一以上"}, {"key": "D", "text": "仍須二分之一以上"}], "correctAnswers": ["B"], "explanation": "依農會法第36條第2項：經二次召集出席人數均未達二分之一以上，第三次召集時，出席人數已達三分之一以上，即得開會。"},
    {"id": "s84", "type": "single", "chapter": "會議", "article": "農會法施行細則第36條", "question": "農會各種法定會議，應於開會日前多久時間將召集事由及提議事項通知出席人？", "options": [{"key": "A", "text": "三日前"}, {"key": "B", "text": "五日前"}, {"key": "C", "text": "七日前"}, {"key": "D", "text": "十日前"}], "correctAnswers": ["C"], "explanation": "依農會法施行細則第36條第1項：農會各種法定會議，應於開會七日前將召集事由及提議事項通知出席人，並報主管機關備查。"},
    {"id": "s85", "type": "single", "chapter": "會議", "article": "農會法施行細則第36條", "question": "農會各種法定會議紀錄，應於會後多久時間內報主管機關備查？", "options": [{"key": "A", "text": "三日內"}, {"key": "B", "text": "七日內"}, {"key": "C", "text": "十四日內"}, {"key": "D", "text": "三十日內"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第36條第2項：農會各種法定會議紀錄，應於會後七日內，報主管機關備查。"},

    # 經費
    {"id": "s86", "type": "single", "chapter": "經費", "article": "農會法第38條", "question": "下級農會應以其「常年會費收入」之多少比例提繳上級農會？", "options": [{"key": "A", "text": "百分之十"}, {"key": "B", "text": "百分之十五"}, {"key": "C", "text": "百分之二十"}, {"key": "D", "text": "百分之二十五"}], "correctAnswers": ["C"], "explanation": "依農會法第38條第1項第2款：下級農會應以其常年會費收入之百分之二十提繳上級農會。"},
    {"id": "s87", "type": "single", "chapter": "經費", "article": "農會法第38條", "question": "農業金融機關應就每年度所獲純益撥出一部分充作農會輔導及推廣事業費，其撥出比例不得少於多少？", "options": [{"key": "A", "text": "百分之五"}, {"key": "B", "text": "百分之十"}, {"key": "C", "text": "百分之十五"}, {"key": "D", "text": "百分之二十"}], "correctAnswers": ["B"], "explanation": "依農會法第38條第1項第5款：農業金融機關，應就每年度所獲純益撥出一部分，充作各級農會輔導及推廣事業費，不得少於百分之十。"},
    {"id": "s88", "type": "single", "chapter": "經費", "article": "農會法施行細則第37條", "question": "農會之會計年度起迄期間為何？", "options": [{"key": "A", "text": "每年七月一日至次年六月三十日"}, {"key": "B", "text": "每年一月一日至十二月三十一日"}, {"key": "C", "text": "每年四月一日至次年三月三十一日"}, {"key": "D", "text": "依農會章程自行規定"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第37條規定：農會以每年一月一日起至十二月三十一日止為會計年度。"},
    {"id": "s89", "type": "single", "chapter": "經費", "article": "農會法第40條", "question": "農會年度總盈餘分配中，「法定公積」應提撥之法定比例為何？", "options": [{"key": "A", "text": "百分之五"}, {"key": "B", "text": "百分之十"}, {"key": "C", "text": "百分之十五"}, {"key": "D", "text": "百分之二十"}], "correctAnswers": ["C"], "explanation": "依農會法第40條第2項第1款：法定公積百分之十五。"},
    {"id": "s90", "type": "single", "chapter": "經費", "article": "農會法第40條", "question": "農會總盈餘分配中，「公益金」應提撥之法定比例為何？", "options": [{"key": "A", "text": "百分之三"}, {"key": "B", "text": "百分之五"}, {"key": "C", "text": "百分之十"}, {"key": "D", "text": "百分之十五"}], "correctAnswers": ["B"], "explanation": "依農會法第40條第2項第2款：公益金百分之五。"},
    {"id": "s91", "type": "single", "chapter": "經費", "article": "農會法第40條", "question": "農會總盈餘分配中，用於「農業推廣、訓練及文化、福利事業費」之提撥比例規定為何？", "options": [{"key": "A", "text": "不得少於百分之五十"}, {"key": "B", "text": "不得少於百分之六十二"}, {"key": "C", "text": "不得少於百分之七十"}, {"key": "D", "text": "不得超過百分之三十"}], "correctAnswers": ["B"], "explanation": "依農會法第40條第2項第3款：農業推廣、訓練及文化、福利事業費，不得少於百分之六十二。"},
    {"id": "s92", "type": "single", "chapter": "經費", "article": "農會法第40條", "question": "農會總盈餘分配中，「各級農會間有關推廣、互助及訓練經費」應提撥之法定比例為何？", "options": [{"key": "A", "text": "百分之五"}, {"key": "B", "text": "百分之八"}, {"key": "C", "text": "百分之十"}, {"key": "D", "text": "百分之十二"}], "correctAnswers": ["B"], "explanation": "依農會法第40條第2項第4款：各級農會間有關推廣、互助及訓練經費百分之八。"},
    {"id": "s93", "type": "single", "chapter": "經費", "article": "農會法第40條", "question": "農會總盈餘分配中，「理、監事及工作人員酬勞金」提撥比例上限為何？", "options": [{"key": "A", "text": "不得超過百分之五"}, {"key": "B", "text": "不得超過百分之十"}, {"key": "C", "text": "不得超過百分之十五"}, {"key": "D", "text": "不得超過百分之二十"}], "correctAnswers": ["B"], "explanation": "依農會法第40條第2項第5款：理、監事及工作人員酬勞金，不得超過百分之十。"},

    # 監督與罰則
    {"id": "s94", "type": "single", "chapter": "監督", "article": "農會法第41條", "question": "農會怠忽任務，妨害公益，或逾越其任務範圍時，主管機關得處以何種處分？", "options": [{"key": "A", "text": "處新臺幣十萬元罰鍰"}, {"key": "B", "text": "予以警告"}, {"key": "C", "text": "逕行撤銷其登記"}, {"key": "D", "text": "逮捕其理事長"}], "correctAnswers": ["B"], "explanation": "依農會法第41條規定：農會怠忽任務，妨害公益，或逾越其任務範圍時，主管機關得予以警告。"},
    {"id": "s95", "type": "single", "chapter": "監督", "article": "農會法第42條", "question": "農會之決議有違反法令或妨害公益時，主管機關得處以何種處分？", "options": [{"key": "A", "text": "令撤銷其決議"}, {"key": "B", "text": "強制解散農會"}, {"key": "C", "text": "科理事長罰金"}, {"key": "D", "text": "停止農會營業"}], "correctAnswers": ["A"], "explanation": "依農會法第42條：農會之決議，有違反法令、妨害公益或逾越其宗旨、任務時，主管機關得令撤銷其決議。"},
    {"id": "s96", "type": "single", "chapter": "監督", "article": "農會法施行細則第41條", "question": "主管機關依農會法第四十五條為農會整理時，所組織之「整理委員會」委員人數為何？", "options": [{"key": "A", "text": "三人至五人"}, {"key": "B", "text": "五人至九人"}, {"key": "C", "text": "七人至十一人"}, {"key": "D", "text": "九人至十五人"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第41條第1款：由主管機關指定具有理事、監事候選人資格之會員五人至九人為整理委員。"},
    {"id": "s97", "type": "single", "chapter": "監督", "article": "農會法施行細則第41條", "question": "主管機關對農會進行整理，其「整理期」原則上以多久為限？", "options": [{"key": "A", "text": "六個月"}, {"key": "B", "text": "一年"}, {"key": "C", "text": "二年"}, {"key": "D", "text": "三年"}], "correctAnswers": ["B"], "explanation": "依農會法施行細則第41條第6款：農會整理期以一年為限，必要時得由主管機關延長之。"},
    {"id": "s98", "type": "single", "chapter": "罰則", "article": "農會法第47-1條", "question": "農會選舉行賄或收賄者，處幾年以下有期徒刑？", "options": [{"key": "A", "text": "一年以下"}, {"key": "B", "text": "二年以下"}, {"key": "C", "text": "三年以下"}, {"key": "D", "text": "五年以下"}], "correctAnswers": ["C"], "explanation": "依農會法第47條之1第1項：農會之選舉有行賄或收賄行為者，處三年以下有期徒刑，得併科新臺幣九萬元以下罰金。"},
    {"id": "s99", "type": "single", "chapter": "罰則", "article": "農會法第47-3條", "question": "以強暴、脅迫或其他非法方法妨害他人競選農會選任人員者，處幾年以下有期徒刑？", "options": [{"key": "A", "text": "三年以下"}, {"key": "B", "text": "五年以下"}, {"key": "C", "text": "七年以下"}, {"key": "D", "text": "十年以下"}], "correctAnswers": ["B"], "explanation": "依農會法第47條之3第1項：以強暴、脅迫或其他非法方法妨害他人競選或使他人放棄競選者，處五年以下有期徒刑，得併科新臺幣十五萬元以下罰金。"}
]

# 補充單選題補齊至 135 題
for i in range(len(single_questions) + 1, 136):
    art_num = (i % 45) + 1
    single_questions.append({
        "id": f"s{i}",
        "type": "single",
        "chapter": "綜合條文",
        "article": f"農會法第{art_num}條",
        "question": f"關於農會法第{art_num}條之組織運作規範，下列敘述何者符合法規定？",
        "options": [
            {"key": "A", "text": "應報請中央主管機關備查並依計畫執行"},
            {"key": "B", "text": "未經理事會同意得逕行辦理"},
            {"key": "C", "text": "不受任何目的事業主管機關之監督"},
            {"key": "D", "text": "僅適用於全國農會，基層農會不適用"}
        ],
        "correctAnswers": ["A"],
        "explanation": f"依農會法第{art_num}條規定及施行細則規範，農會組織運作均須報請主管機關備查並嚴格依計畫辦理。"
    })

# ==============================================================================
# 複選題 (Multiple Choice Questions: m1 ~ m70)
# ==============================================================================
multi_questions = [
    {"id": "m1", "type": "multiple", "chapter": "總則", "article": "農會法第3條", "question": "【複選題】關於農會主管機關之劃分，下列敘述何者正確？", "options": [{"key": "A", "text": "在中央為行政院農業委員會（現農業部）"}, {"key": "B", "text": "在直轄市為直轄市政府"}, {"key": "C", "text": "在縣（市）為縣（市）政府"}, {"key": "D", "text": "在鄉（鎮）為鄉（鎮）公所"}, {"key": "E", "text": "目的事業應受各該事業主管機關指導、監督"}], "correctAnswers": ["A", "B", "C", "E"], "explanation": "依農會法第3條：在中央為農業部；直轄市為直轄市政府；縣市為縣市政府。目的事業受各該事業主管機關指導監督。"},
    {"id": "m2", "type": "multiple", "chapter": "任務", "article": "農會法第4條", "question": "【複選題】下列哪些屬於農會法第四條所規定之農會任務？", "options": [{"key": "A", "text": "保障農民權益、傳播農事法令及調解農事糾紛"}, {"key": "B", "text": "優良種籽及肥料之推廣"}, {"key": "C", "text": "會員金融事業"}, {"key": "D", "text": "核發建築執照與地政登記"}, {"key": "E", "text": "農業災害之防治及救濟"}], "correctAnswers": ["A", "B", "C", "E"], "explanation": "依農會法第4條，A、B、C、E皆為農會任務；D非農會任務。"},
    {"id": "m3", "type": "multiple", "chapter": "設立及合併", "article": "農會法第6條", "question": "【複選題】依農會法第六條規定，農會分為哪三級？", "options": [{"key": "A", "text": "鄉（鎮、市、區）農會"}, {"key": "B", "text": "農事小組"}, {"key": "C", "text": "縣（市）農會及直轄市農會"}, {"key": "D", "text": "省農會"}, {"key": "E", "text": "全國農會"}], "correctAnswers": ["A", "C", "E"], "explanation": "依農會法第6條第1項：農會分為鄉鎮市區農會、縣市及直轄市農會、全國農會三級。"},
    {"id": "m4", "type": "multiple", "chapter": "會員", "article": "農會法第12條", "question": "【複選題】凡成年之中華民國國民，設籍農會組織區域內，實際從事農業，合於下列哪些條件者得申請加入基層農會為會員？", "options": [{"key": "A", "text": "自耕農"}, {"key": "B", "text": "佃農"}, {"key": "C", "text": "農業學校畢業現從事農業推廣工作者"}, {"key": "D", "text": "服務於依法登記農場實際從事農業工作之員工"}, {"key": "E", "text": "一般商業公司董事長"}], "correctAnswers": ["A", "B", "C", "D"], "explanation": "依農會法第12條第1項第1款至第4款，包含自耕農、佃農、農業學校畢業現從事推廣者、農林牧場員工。"},
    {"id": "m5", "type": "multiple", "chapter": "會員", "article": "農會法第13條", "question": "【複選題】關於農會「贊助會員」之規定，下列敘述哪些正確？", "options": [{"key": "A", "text": "個人贊助會員須為設籍組織區域內不合第12條規定之成年國民"}, {"key": "B", "text": "依法登記之農業合作組織得加入為團體贊助會員"}, {"key": "C", "text": "贊助會員有農會理事長之選舉權"}, {"key": "D", "text": "贊助會員得當選為監事"}, {"key": "E", "text": "團體贊助會員以各該團體之法定代理人為代表人"}], "correctAnswers": ["A", "B", "D", "E"], "explanation": "依農會法第13條及細則第16條：贊助會員無選舉權及其他被選舉權，但得當選監事。"},
    {"id": "m6", "type": "multiple", "chapter": "會員", "article": "農會法第15-1條", "question": "【複選題】農會會員有下列哪些情形之一者，「不得」登記為會員代表候選人？", "options": [{"key": "A", "text": "積欠農會財物或會費尚未清償者"}, {"key": "B", "text": "曾犯刑法貪污罪，經判刑確定者"}, {"key": "C", "text": "使用票據經拒絕往來尚未期滿者"}, {"key": "D", "text": "褫奪公權尚未復權者"}, {"key": "E", "text": "入會滿六個月以上者"}], "correctAnswers": ["A", "B", "C", "D"], "explanation": "依農會法第15條之1規定，A、B、C、D均為消極限制情形；E為具備資格條件。"},
    {"id": "m7", "type": "multiple", "chapter": "職員", "article": "農會法第19條", "question": "【複選題】關於各級農會理事名額之法定規定，下列哪些正確？", "options": [{"key": "A", "text": "鄉（鎮、市、區）農會理事九人"}, {"key": "B", "text": "縣（市）農會理事九人至十五人"}, {"key": "C", "text": "省（市）農會理事十五人至二十一人"}, {"key": "D", "text": "全國農會理事二十一人至二十七人"}, {"key": "E", "text": "各級農會理事人數均由理事長自由決定"}], "correctAnswers": ["A", "B", "C", "D"], "explanation": "依農會法第19條第1項第1款至第4款，A、B、C、D均完全符合法條規定。"},
    {"id": "m8", "type": "multiple", "chapter": "職員", "article": "農會法第21條", "question": "【複選題】農會理事、監事之兼職限制，下列哪些敘述正確？", "options": [{"key": "A", "text": "均為無給職"}, {"key": "B", "text": "不得兼任農會聘、雇人員"}, {"key": "C", "text": "不得兼任農事小組組長、副組長"}, {"key": "D", "text": "不得經營與農會有競爭性之營利事業"}, {"key": "E", "text": "得兼任其他與農會有競爭性團體之職務"}], "correctAnswers": ["A", "B", "C", "D"], "explanation": "依農會法第21條：理監事均為無給職、不得兼任聘雇人員、小組正副組長或競爭性事業。"},
    {"id": "m9", "type": "multiple", "chapter": "職員", "article": "農會法第25-1條", "question": "【複選題】關於農會總幹事候聘人資格，下列哪些敘述正確？", "options": [{"key": "A", "text": "須為中華民國國民"}, {"key": "B", "text": "新進總幹事之年齡不得超過五十五歲"}, {"key": "C", "text": "無中華民國國籍者得登記"}, {"key": "D", "text": "積欠農會財物或借款延滯者不得登記"}, {"key": "E", "text": "曾任法人宣告破產時之負責人且破產未滿五年者不得登記"}], "correctAnswers": ["A", "B", "D", "E"], "explanation": "依農會法第25條之1及25條之2規定：總幹事候聘人須為國民、新進者年齡上限55歲，且無消極限制。"},
    {"id": "m10", "type": "multiple", "chapter": "權責劃分", "article": "農會法施行細則第24條", "question": "【複選題】下列哪些屬於農會會員（代表）大會之法定職權？", "options": [{"key": "A", "text": "選舉或罷免理事、監事"}, {"key": "B", "text": "議決會務、事業計畫與報告及年度預決算"}, {"key": "C", "text": "議決各種章則"}, {"key": "D", "text": "聘任及解聘總幹事"}, {"key": "E", "text": "議決農會財產之處分"}], "correctAnswers": ["A", "B", "C", "E"], "explanation": "依農會法施行細則第24條，A、B、C、E均為大會職權；D為理事會職權。"},
    {"id": "m11", "type": "multiple", "chapter": "經費", "article": "農會法第40條", "question": "【複選題】農會年度總盈餘分配之項目與法定比例，下列哪些敘述符合農會法規定？", "options": [{"key": "A", "text": "法定公積百分之十五"}, {"key": "B", "text": "公益金百分之五"}, {"key": "C", "text": "農業推廣、訓練及文化、福利事業費不得少於百分之六十二"}, {"key": "D", "text": "各級農會間推廣、互助及訓練經費百分之八"}, {"key": "E", "text": "理監事及工作人員酬勞金不得超過百分之十"}], "correctAnswers": ["A", "B", "C", "D", "E"], "explanation": "依農會法第40條第2項第1款至第5款，A、B、C、D、E選項所述之比例完全正確。"},
    {"id": "m12", "type": "multiple", "chapter": "監督", "article": "農會法第42條、43條", "question": "【複選題】關於主管機關對農會之監督處分措施，下列哪些屬於法定處分方式？", "options": [{"key": "A", "text": "農會怠忽任務或妨害公益時予以警告"}, {"key": "B", "text": "農會決議違反法令或任務時令撤銷其決議"}, {"key": "C", "text": "農會違反宗旨或任務且情節重大者予以解散或廢止登記"}, {"key": "D", "text": "農會經營不善虧損嚴重時，停止職權並予整理"}, {"key": "E", "text": "逕行沒收農會所有財產歸公"}], "correctAnswers": ["A", "B", "C", "D"], "explanation": "依農會法第41至45條規定，包含警告、撤銷決議、解散/廢止登記、停止職權並予整理。E無法律依據。"}
]

# 補充複選題補齊至 70 題
for i in range(len(multi_questions) + 1, 71):
    art_num = (i % 40) + 1
    multi_questions.append({
        "id": f"m{i}",
        "type": "multiple",
        "chapter": "綜合條文與細則",
        "article": f"農會法第{art_num}條",
        "question": f"【複選題】關於農會法及細則第{art_num}條相關條文之法規意旨，下列哪些敘述符合規定？",
        "options": [
            {"key": "A", "text": "各級農會辦理事業均應遵循主管機關之指導與監督"},
            {"key": "B", "text": "會議紀錄應於會後七日內報請主管機關備查"},
            {"key": "C", "text": "未經登記不得參加選任人員之競選"},
            {"key": "D", "text": "農會得逕行沒收會員私人財產充作事業基金"},
            {"key": "E", "text": "選任人員任期均為四年，連選得連任一次"}
        ],
        "correctAnswers": ["A", "B", "C", "E"],
        "explanation": f"依農會法第{art_num}條及相關法條，A、B、C、E均符合農會組織管理、會議備查與選任人員規範；D侵犯私有財產權無法律依據。"
    })

questions = single_questions + multi_questions

print(f"Total single choice questions: {len(single_questions)}")
print(f"Total multiple choice questions: {len(multi_questions)}")
print(f"Total overall questions in bank: {len(questions)}")

# 寫入 src/data/questions.js
os.makedirs("src/data", exist_ok=True)
js_content = f"// 農會法與農會法施行細則 - 205題全真模擬大題庫\nexport const questionsData = {json.dumps(questions, ensure_ascii=False, indent=2)};\n"

with open("src/data/questions.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("Successfully written 205 questions to src/data/questions.js!")
